- name: Run PostgreSQL container from Docker Hub
  community.docker.docker_container:
    name: my_db
    image: mrjj001/tp-devops-database
    pull: true
    recreate: true
    env:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    networks:
      - name: my_app_network
    state: started
    restart_policy: always
